route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'ses'
receivers:
  - name: 'ses'
    email_configs:
      - smarthost: email-smtp.us-east-1.amazonaws.com:587
        auth_username: AKIAZRGWJBJYCLNVAWZV
        auth_password: BLxQ98uBClegu4f+dDJtBgYbdwz+c2sUvqZs97l+ZSGs
        from: bnarayanaswamy27@gmail.com
        to: bnarayanaswamy27@gmail.com
        headers:
          subject: Prometheus Mail Alert
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
